### ISSUE TITLE
SiRi to Ex calibrationfrom batch file

### ISSUE THREAD

**Issue by fzeiser** [vetlewi/OfflineOCL#2]
I want to be able to read the excitation energy calibration from the batch file, thus I inserted a line to read a new parameter here:

https://github.com/vetlewi/OfflineOCL/blob/ce211c45f6422f3b2295e032202eacd8d1812f1f/XIAreader/source/userroutine/src/UserSort.cpp#L74-L83 
`, ex_from_ede    ( GetParameters(), "ex_from_ede", NUM_SI_RINGS*3, 0)`

and put the corresponding statement in the header file and in the batch file.

However, got stuck in how to convert following line: 
https://github.com/vetlewi/OfflineOCL/blob/ce211c45f6422f3b2295e032202eacd8d1812f1f/XIAreader/source/userroutine/src/UserSort.cpp#L264

To something like
`double ex = ex_from_ede[3*dei+0] + (e_energy+de_energy)*(ex_from_ede[3*dei+1] + (e_energy+de_energy)*(e_energy+de_energy)*ex_from_ede[3*dei+2]);`

How to I retrieve the ring number of a current event?

**Comment by vetlewi** [comment]
This is implemented, so I'm closing it!
