### ISSUE TITLE
Error in handling of fission?

### ISSUE THREAD

**Issue by dortheg** [vetlewi/OfflineOCL#21]
Fabio and I think there is an error in the handling of fission. 

Now, the code loops over each event in the ppacs, and puts the variable ppac_prompt to either true or false, before checking if the labr are prompt. 

The result is that if there are several events in the ppacs, it will only be counted as one true or false event. If, for example, there are two events in the ppacs, and they are true and then false respectively, (we think) ppac_prompt will be put to false, which throws away a good event.

Instead, for each event in the ppacs, one should check if the labr are prompt or not.

https://github.com/vetlewi/OfflineOCL/blob/10c6c3a29132ca4cd9c4c778f6d802d40bf02c3a/XIAreader/source/userroutine/src/UserSort.cpp#L594-L617

**Comment by vetlewi** [comment]
If line 606 is removed it should work fine. However, this should only be an issue if there are multiple PPACs within the event (3 us). I don't know what the cross-section for fission is, but I would have thought the probability is very low of two fission events within 3 us.
