### ISSUE TITLE
Import all commands (we've had previously) from batch file 

### ISSUE THREAD

**Issue by fzeiser** [vetlewi/OfflineOCL#3]
How about importing all commands we've had in the usersort he way it's done in
https://github.com/oslocyclotronlab/usersort ?

If you @Vetle don't have plans to do this, you can assign me and I'll do it as soon as I have some data to sort.

**Comment by vetlewi** [comment]
I'm not sure we need to import all the parameters we used previously. Since we now have CFD on all channels we don't need correction to the time spectra, etc. I think things should be implemented once it turns out that they are needed.

**Comment by fzeiser** [comment]
Sure, you're right. The comment was done before we implemented reading anything from the batch file...
