### ISSUE TITLE
Create a alfna matrix (incl bg subtraction)

### ISSUE THREAD

**Issue by fzeiser** [vetlewi/OfflineOCL#4]
I saw that there was an initial attempt to create a alfna (target excitation(particle)-gamma coincidence ) matrix  called alfna_labr_1 in 690468b1f90b865c13087d5fef428864229af52d.

It has been removed in ce211c45f6422f3b2295e032202eacd8d1812f1f.

I think it would be good to get this back again,  probably combined with an import of the parameters that should be used as specified in #3.

@vetlewi: How far did you proceed on this? Unless you have done it (and just not uploaded), I can do this once I copy some data from you on Thursday, or with my own data on Monday.
(-> Assign me or yourself, depending on whom you think should do it).

**Comment by vetlewi** [comment]
This has been implemented. Closing the issue
